### ISSUE TITLE
Does not use most recent version of babe-project

### ISSUE THREAD

**Issue by JannisBush** [babe-project/departure-point#1]
Currently, it uses version `0.0.25`, which has a "bad" `babe.css`-file. (Pictures are displayed too large and overlap with the questions.)

As this is our example, it think it should always use the most recent version of `babe-project`.
Otherwise people will clone this repository and work with an old version `babe-project`.
Therefore we should exchange the fixed version number in `package.json` with something like `latest` or `0.x` or `^0.0.26`. I'm not sure what the best/correct way would be, but the fixed version number is definitely not the best idea.

**Comment by x-ji** [comment]
Usually one fixes the version number when the software is stable. This repo is a bit special in that it is intended to serve as a template/scaffold from which new projects are to be developed. Therefore it might just make sense to depend on the newest `babe-project` version provided that each commit is tested to work well.

**Comment by JannisBush** [comment]
Yes,  we could depend on the newest `babe-project` version and push all changes to prereleases using the `next`-tag, so the normal users won't see them, test them and then push them to `latest`.

**Comment by x-ji** [comment]
Another thing is to fix a major version, e.g. `^1.0.0`, and ensure that every new release of `babe-project` in that major version is compatible with a previous release. Breaking changes to `babe-project` would happen in the next major version, so this package wouldn't be affected anyways.

Or fix a minor version such as `~0.1.0`, if we haven't released any major version yet.

**Comment by JannisBush** [comment]
Fixing the minor version is probably the best way for now.
We still can use prereleases to make it easier for us to test the new versions.

**Comment by JannisBush** [comment]
Apparently using `^` in versions prior to `1.0.0` does not work. 
I now fixed it to the minor version.
