### ISSUE TITLE
Flatten the value to be submitted under the "canvas" key

### ISSUE THREAD

**Issue by x-ji** [babe-project/departure-point#2]
See https://github.com/babe-project/BABE/issues/72

**Comment by JannisBush** [comment]
In the debug environment it is also not working correctly and just displays `[object Object]` on the result page as well as in the downloaded csv-file.

![](https://i.imgur.com/QbB7z2R.png)

**Comment by JannisBush** [comment]
This is fixed with version 0.0.27 of babe-project https://github.com/babe-project/babe-project/pull/35
