### ISSUE TITLE
embed sound files?

### ISSUE THREAD

**Issue by timo-b-roettger** [babe-project/departure-point#4]
Great tool! Is there a convenient way to embed sound files into the experiments? (can't find any info on that in the documentation)

**Comment by michael-franke** [comment]
Unfortunately, there is no ready-made template for this. You would need to create a custom view by writing your own stimulus contain-function that embeds the sound file using, e.g., a standard HTML audio-tag.

See here on custom views:
https://babe-project.github.io/babe-docs/01_designing_experiments/03_custom_views/

But I agree that a ready-made stimulus container-function for audio and video would be handy!
